# Generated by Django 4.2.4 on 2023-08-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('sports_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sports')),
            ],
        ),
    ]
